format = """
[ 󰣇 ](bg:#a7c080 fg:#272e33)\
$directory\
[](fg:#a7c080 bg:#4f5b57)\
$git_branch\
$git_status\
[](fg:#4f5b57 bg:#2e383c)\
$c\
$rust\
$golang\
$python\
[](fg:#2e383c bg:#272e33)\
$time\
[ ](fg:#272e33)\
\n$character"""

right_format = """
$cmd_duration
"""

[cmd_duration]
format = "[ $duration ](italic fg:#a7c080)"

[directory]
style = "fg:#272e33 bg:#a7c080"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#5c6a72"
format = '[[ $symbol $branch ](fg:#bec5b2 bg:#4f5b57)]($style)'

[git_status]
style = "bg:#5c6a72"
format = '[[($all_status$ahead_behind )](fg:#bec5b2 bg:#4f5b57)]($style)'

[c]
symbol = ""
style = "bg:#2e383c"
format = '[[ $symbol ($version) ](fg:#9da9a0 bg:#2e383c)]($style)'

[rust]
symbol = ""
style = "bg:#2e383c"
format = '[[ $symbol ($version) ](fg:#9da9a0 bg:#2e383c)]($style)'

[golang]
symbol = ""
style = "bg:#2e383c"
format = '[[ $symbol ($version) ](fg:#9da9a0 bg:#2e383c)]($style)'

[python]
symbol = "🐍"
style = "bg:#2e383c"
format = '[[ $symbol ($version) ](fg:#9da9a0 bg:#2e383c)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#272e33"
format = '[[  $time ](fg:#a7c080 bg:#272e33)]($style)'

[character]
disabled = false
success_symbol = '[](bold fg:#a7c080)'
error_symbol = '[](bold fg:#e67e80)'
vimcmd_symbol = '[](bold fg:#a7c080)'
vimcmd_replace_one_symbol = '[](bold fg:#b16286)'
vimcmd_replace_symbol = '[](bold fg:#b16286)'
vimcmd_visual_symbol = '[](bold fg:#d79921)'
